// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: arka/subscription/v1beta1/genesis.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Nonce, Plan, PlanPurchase } from "./subscription";

export const protobufPackage = "arka.subscription.v1beta1";

/** GenesisState defines the subscription module's genesis state. */
export interface GenesisState {
  planSeq: number;
  plans: Plan[];
  purchasedPlans: PlanPurchase[];
  nonce: Nonce[];
}

function createBaseGenesisState(): GenesisState {
  return { planSeq: 0, plans: [], purchasedPlans: [], nonce: [] };
}

export const GenesisState = {
  encode(message: GenesisState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.planSeq !== 0) {
      writer.uint32(8).uint64(message.planSeq);
    }
    for (const v of message.plans) {
      Plan.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    for (const v of message.purchasedPlans) {
      PlanPurchase.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    for (const v of message.nonce) {
      Nonce.encode(v!, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.planSeq = longToNumber(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.plans.push(Plan.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.purchasedPlans.push(PlanPurchase.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.nonce.push(Nonce.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      planSeq: isSet(object.planSeq) ? globalThis.Number(object.planSeq) : 0,
      plans: globalThis.Array.isArray(object?.plans) ? object.plans.map((e: any) => Plan.fromJSON(e)) : [],
      purchasedPlans: globalThis.Array.isArray(object?.purchasedPlans)
        ? object.purchasedPlans.map((e: any) => PlanPurchase.fromJSON(e))
        : [],
      nonce: globalThis.Array.isArray(object?.nonce) ? object.nonce.map((e: any) => Nonce.fromJSON(e)) : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.planSeq !== 0) {
      obj.planSeq = Math.round(message.planSeq);
    }
    if (message.plans?.length) {
      obj.plans = message.plans.map((e) => Plan.toJSON(e));
    }
    if (message.purchasedPlans?.length) {
      obj.purchasedPlans = message.purchasedPlans.map((e) => PlanPurchase.toJSON(e));
    }
    if (message.nonce?.length) {
      obj.nonce = message.nonce.map((e) => Nonce.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.planSeq = object.planSeq ?? 0;
    message.plans = object.plans?.map((e) => Plan.fromPartial(e)) || [];
    message.purchasedPlans = object.purchasedPlans?.map((e) => PlanPurchase.fromPartial(e)) || [];
    message.nonce = object.nonce?.map((e) => Nonce.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
